---
title: "Pr_1_V4"
author: "Robert McNeil"
date: "2024-09-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo= FALSE}
#load libraries 
library(tidyverse)
library(dplyr)
library(lme4)
library(ggplot2)

#read the dataset
gum <-read.csv("/home/robmcneil/Documents/advanced_data/Project1_data.csv")

```


```{r, echo=FALSE}

#create base attachment and pocket depth outcome variables 
gum <- gum %>%
  mutate( 
    attach = attach1year - attachbase,
    pd     = pd1year    - pdbase
  )
```


```{r,echo=FALSE}

#one possible for regression- create dumy variables for groups?
gum_with_groups <-gum %>%
  mutate(
    group1 = if_else(trtgroup == 1,1,0),
    group2 = if_else(trtgroup == 2,1,0),
    group3 = if_else(trtgroup == 3,1,0),
    group4 = if_else(trtgroup == 4,1,0),
    group5 = if_else(trtgroup == 5,1,0)
  )

```

```{r, echo=FALSE}
#fit a model with my groups as dummy variables
model_attach <- lm(attach ~ group1 +group3 +group4 +group5, data = gum_with_groups)
model_attach
summary(model_attach)
#make additional model for group 2

```


```{r, echo= FALSE}
#model attachment loss with no groups
model_att_factored <- lm(attach ~ factor(trtgroup), data =gum)
summary(model_att_factored)

#zoey added this in 
gum$trtgroup<-group(gum$trtgroup2)
model_att_test <- lm(attach ~ trtgroup2)

```

```{r, echo = FALSE}
#test assumption of linearity 
#dont need to test for linearity with categorical variables 
ggplot(gum, aes(x = factor(trtgroup), y = attach, color = factor(trtgroup))) +
  geom_point() +
  labs(
    title = "Scatter Plot of Attachment Loss by Treatment Group",
    x = "Treatment Group",
    y = "Attachment Loss",
    color = "Treatment Group"
  ) +
  theme_minimal()
```


```{r, echo = FALSE}

ggplot(gum, aes(x = factor(trtgroup), y = pd, color = factor(trtgroup))) +
  geom_point() +
  labs(
    title = "Scatter Plot of Pocket Depth by Treatment Group",
    x = "Treatment Group",
    y = "Pocket Depth",
    color = "Treatment Group"
  ) +
  theme_minimal()

```
```{r, echo = false}
#extract residuals from attachment loss model 
#test normality with a Q-Q plot 
res_attach <- resid(model_attach)
qqnorm(res_attach)
qqline(res_attach)
```
#noted tiny outlier, ew may need to study in further stufy 



